<<<<<<< Updated upstream
# Generated by Django 5.0.8 on 2024-09-04 16:08
=======
# Generated by Django 5.0.8 on 2024-08-24 21:26
>>>>>>> Stashed changes

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactDB',
            new_name='AboutDB',
        ),
    ]
