<<<<<<< Updated upstream
# Generated by Django 5.0.8 on 2024-09-04 16:08
=======
# Generated by Django 5.0.8 on 2024-08-24 21:26
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
<<<<<<< Updated upstream
                ('dateblog', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=100)),
=======
>>>>>>> Stashed changes
                ('img', models.ImageField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
    ]
