# Generated by Django 5.0.8 on 2024-09-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdb',
            name='dateblog',
            field=models.DateField(blank=True, null=True),
        ),
    ]
