# Generated by Django 5.0.8 on 2024-09-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogdb_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdb',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
